### ISSUE TITLE
Keep specific items 

### ISSUE THREAD

**Issue by Morgy93** [stef-levesque/vscode-multiclip#4]
I'd like to have some checkbox next to the items, so that it will stay in the clipboard after other 10 items have been copied/cut.
Like I got two items in the clipboard which I need multiple times but meanwhile I copy and paste other stuff and the two items I need all the times are then wiped out of the clipboard.
So some feature that is able to "stick" the items in the clipboard would be awesome.

**Comment by stef-levesque** [comment]
Afaik, there is no way to add a checkbox in vscode palette.

If you update to version 0.1.0, you have two new options:

- @TimMensch has added a new feature to Merge-Copy into the same item. Hopefully this should help reduce the item used.

- Otherwise, you can now configure the maximum number of item to keep in the multiclip buffer (see README.md)
